name: prod

on:
  push:  
    branches:
      - 'master'

jobs:
  prod:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "14.18.0"
          
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ./node_modules
          key: ${{ runner.os }}-build-cache-node-modules-${{ hashFiles('**/package.json') }}
          restore-keys: |
            cache-node-modules-
            
      - name: Run ci
        run: |
          npm install
          npm run ci

      - name: cd
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: 'root'   #ssh user name
          server: '${{ secrets.SERVER_IP }}' #引用之前创建好的secret
          password: '${{ secrets.SERVER_PASSWORD }}'
          port: 22
          local_path: './dist/*'  # 对应我们项目build的文件夹路径
          remote_path: '/www/wwwroot/assets/ConsoleGame'
